http.host: 0.0.0.0

# Uncomment the following lines for a production cluster deployment
#transport.host: 0.0.0.0
#discovery.zen.minimum_master_nodes: 1

### x-pack functions
xpack.security.enabled: false
xpack.monitoring.enabled: true
xpack.graph.enabled: false
xpack.watcher.enabled: false
# https://discuss.elastic.co/t/errors-after-installing-x-pack/64210/7
xpack.monitoring.exporters.my_local:
  type: local
  use_ingest: false